### PR TITLE
#912 Fix bug - new version package can not use old version package's db

### LINKED ISSUE #912: 【异步调用功能】Platform-core支持插件接口参数为constant类型
**描述您的需求** 
由于目前插件注册时只支持context、systemVariable、DME三种参数类型，但这些类型未覆盖服务管理接口参数的类型，所以需要修改插件注册，使插件接口参数支持constant类型，该类型参数在流程编排的时候输入值。

### PR DESCRIPTION
**Pull request by haixinhuang**
Fixed #912

### CODE REVIEW

File: platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java [hunk 1]
```diff
@@ -222,16 +222,19 @@ private DatabaseInfo handleCreateDatabase(Set<PluginPackageRuntimeResourcesMysql
...
-        List<PluginMysqlInstance> mysqlInstances = pluginMysqlInstanceRepository
-                .findBySchemaNameAndStatus(pluginPackage.getName(), PluginMysqlInstance.MYSQL_INSTANCE_STATUS_ACTIVE);
-        if (mysqlInstances.size() > 0) {
-            PluginMysqlInstance mysqlInstance = mysqlInstances.get(0);
-            ResourceServer resourceServer = mysqlInstance.getResourceItem().getResourceServer();
-            return new DatabaseInfo(resourceServer.getHost(), resourceServer.getPort(), mysqlInstance.getSchemaName(),
-                    mysqlInstance.getUsername(), mysqlInstance.getPassword(), mysqlInstance.getResourceItemId());
-        } else {
-            return initMysqlDatabaseSchema(mysqlInfoSet, pluginPackage);
+        List<PluginPackage> sameNamePackages = pluginPackageRepository.findAllByName(pluginPackage.getName());
```
Comment (BenJaMiniature) [inline platform-core/src/main/java/com/webank/wecube/platform/core/service/PluginInstanceService.java]: Adding a method in PluginMysqlInstanceRepository can make the logic simpler.

    List<PluginMysqlInstance> findByStatusAndPluginPackage_name(String status, String packageName);
